### ISSUE TITLE
Add Toaq keyboard

### ISSUE THREAD

**Issue by Zig-Rust-Odin** [toaq/toadua-android#17]
Add Toaq keyboard
https://f-droid.org/packages/dev.patrickgold.florisboard/
https://f-droid.org/packages/org.fcitx.fcitx5.android/ 
fcitx5 can generate Toaq keyboard apps via plugin

**Comment by robintown** [comment]
Mobile Toaq input methods are out of scope for this project, though you can check out https://toaq.me/Input_methods#Phones
